import type {
  BpmProduct, BpmPromotion, BpmGoodie, BpmCompetitor, BpmNotification, BpmIntegration,
} from './types';

export const PRODUCTS: BpmProduct[] = [
  { id: 'P001', name: 'Berliner Fernsehturm Limited Edition 2026', cat: 'Limited Edition', series: 'Stadtikonen',
    status: 'kritisch', year: 2026, parts: 2450, uvp: 249.95, price: 249.95, cost: 112.48, tMgn: 0.50, mMgn: 0.35,
    stock: 38, minStock: 50, validFrom: '2026-01-15', validTo: null, channel: 'Online, POS', succ: 'P010',
    descr: 'Ikonisches Berliner Wahrzeichen als hochdetailliertes Klemmbausteinmodell. Limitierte Auflage 2026. Nummeriertes Echtheitszertifikat inklusive. 2.450 Teile.' },
  { id: 'P002', name: 'Hamburger Speicherstadt Architektur-Set', cat: 'Architektur-Set', series: 'Deutsche Architektur',
    status: 'aktiv', year: 2026, parts: 1850, uvp: 129.95, price: 129.95, cost: 58.48, tMgn: 0.45, mMgn: 0.35,
    stock: 142, minStock: 30, validFrom: '2026-02-01', validTo: null, channel: 'Online', succ: null,
    descr: 'Die historische Hamburger Speicherstadt in beeindruckender Detailtreue. 1.850 Teile. Maßstab 1:350.' },
  { id: 'P003', name: 'Alte Försterei Stadion-Set 2025', cat: 'Stadion-Set', series: 'Bundesliga Arenen',
    status: 'aktiv', year: 2025, parts: 2100, uvp: 149.95, price: 139.95, cost: 67.48, tMgn: 0.45, mMgn: 0.35,
    stock: 89, minStock: 40, validFrom: '2025-09-01', validTo: '2026-12-31', channel: 'Online, POS', succ: null,
    descr: 'Detailgetreues Abbild des Stadions an der Alten Försterei. 2.100 Teile. Inkl. Außenanlagen und Fanblock-Bestuhlung.' },
  { id: 'P004', name: 'Rhein-Main Arena Stadion-Set 2026', cat: 'Stadion-Set', series: 'Bundesliga Arenen',
    status: 'aktiv', year: 2026, parts: 2800, uvp: 169.95, price: 169.95, cost: 76.48, tMgn: 0.45, mMgn: 0.35,
    stock: 64, minStock: 40, validFrom: '2026-03-01', validTo: null, channel: 'Online', succ: null,
    descr: 'Neue Rhein-Main Arena in Frankfurt. 2.800 Teile. Inkl. Dach und Spielfeld-Detailansicht.' },
  { id: 'P005', name: 'Hafenkran Architekturmodell 2025', cat: 'Architektur-Set', series: 'Industrieikonen',
    status: 'ausgelaufen', year: 2025, parts: 1200, uvp: 89.95, price: 74.95, cost: 42.48, tMgn: 0.45, mMgn: 0.35,
    stock: 12, minStock: 20, validFrom: '2025-03-01', validTo: '2026-06-30', channel: 'Online', succ: null,
    descr: 'Klassischer Hafenkran aus der Hamburger Werftgeschichte. Auslaufmodell – Abverkauf aktiv.' },
  { id: 'P006', name: 'Einzelstein-Box Basic 2024', cat: 'Einzelstein-Box', series: 'Steine & Teile',
    status: 'aktiv', year: 2024, parts: 500, uvp: 19.95, price: 19.95, cost: 6.98, tMgn: 0.45, mMgn: 0.30,
    stock: 340, minStock: 100, validFrom: '2024-01-01', validTo: null, channel: 'Online, POS', succ: null,
    descr: '500 Einzelsteine sortiert nach Farbe. Classic-Farbsortierung. Für Sammler und Bastler.' },
  { id: 'P007', name: 'Einzelstein-Box Pro 2026', cat: 'Einzelstein-Box', series: 'Steine & Teile',
    status: 'geplant', year: 2026, parts: 1000, uvp: 59.95, price: 59.95, cost: 22.48, tMgn: 0.45, mMgn: 0.30,
    stock: 0, minStock: 50, validFrom: '2026-09-01', validTo: null, channel: 'Online', succ: null,
    descr: '1.000 Einzelsteine in Pro-Selektion. Spezialfarben und Sondersteine. Launch September 2026.' },
  { id: 'P008', name: 'Ersatzteilservice Standard', cat: 'Ersatzteilservice', series: 'Service',
    status: 'aktiv', year: 2024, parts: 0, uvp: 2.99, price: 2.99, cost: 0.89, tMgn: 0.55, mMgn: 0.40,
    stock: 999, minStock: 0, validFrom: '2024-01-01', validTo: null, channel: 'Online', succ: null,
    descr: 'Monatliches Ersatzteil-Abo. Bis zu 5 Ersatzteile pro Monat. Kostenloser Versand.' },
  { id: 'P009', name: 'Ersatzteilservice Plus', cat: 'Ersatzteilservice', series: 'Service',
    status: 'aktiv', year: 2024, parts: 0, uvp: 7.99, price: 7.99, cost: 2.39, tMgn: 0.55, mMgn: 0.40,
    stock: 999, minStock: 0, validFrom: '2024-01-01', validTo: null, channel: 'Online', succ: null,
    descr: 'Premium Ersatzteil-Abo. Unbegrenzte Ersatzteile, Express-Versand, Sammler-Vorteile.' },
  { id: 'P010', name: 'Skyline Berlin Nachtedition 2026 (Preorder)', cat: 'Preorder-Produkt', series: 'Stadtikonen',
    status: 'preorder', year: 2026, parts: 3100, uvp: 199.95, price: 189.95, cost: 89.98, tMgn: 0.50, mMgn: 0.38,
    stock: 0, minStock: 500, validFrom: '2026-04-01', validTo: '2026-09-30', channel: 'Online', succ: null,
    descr: 'Limitierter Preorder. Berliner Skyline im Nacht-Design. 3.100 Teile. Lieferung Oktober 2026.' },
  { id: 'P011', name: 'Sammlerbundle Stadion Duo 2026', cat: 'Bundle', series: 'Bundle-Sets',
    status: 'aktiv', year: 2026, parts: 0, uvp: 269.95, price: 269.95, cost: 121.48, tMgn: 0.45, mMgn: 0.38,
    stock: 28, minStock: 15, validFrom: '2026-03-15', validTo: null, channel: 'Online', succ: null,
    descr: 'Bundle aus Alte Försterei + Rhein-Main Arena. Inkl. exklusivem Stadion-Poster. Sonderausgabe.' },
  { id: 'P012', name: 'LED-Kit Architektur', cat: 'Zubehör', series: 'Zubehör & Extras',
    status: 'aktiv', year: 2025, parts: 0, uvp: 39.95, price: 39.95, cost: 14.98, tMgn: 0.45, mMgn: 0.35,
    stock: 87, minStock: 30, validFrom: '2025-06-01', validTo: null, channel: 'Online', succ: null,
    descr: 'LED-Beleuchtungskit für Architektur-Sets. USB-betrieben. Einfache Montage. Universell einsetzbar.' },
  { id: 'P013', name: 'Display Case Premium', cat: 'Zubehör', series: 'Zubehör & Extras',
    status: 'aktiv', year: 2025, parts: 0, uvp: 49.95, price: 49.95, cost: 18.73, tMgn: 0.45, mMgn: 0.35,
    stock: 45, minStock: 20, validFrom: '2025-06-01', validTo: null, channel: 'Online, POS', succ: null,
    descr: 'Hochwertige Acryl-Vitrine für Klemmbausteinmodelle. Staubschutz und UV-Schutz. Diverse Größen.' },
];

export const PROMOTIONS: BpmPromotion[] = [
  { id: 'A001', name: 'Fernsehturm Abverkaufs-Aktion', productId: 'P001', type: 'Abverkauf', startDate: '2026-06-20',
    endDate: '2026-07-15', targetUnits: 38, sold: 14, targetRev: 9500, expMgn: 0.50, status: 'aktiv',
    note: 'Rabatt 10% + Goodie Teiletrenner empfohlen' },
  { id: 'A002', name: 'Preorder Skyline Berlin – Sommer-Kampagne', productId: 'P010', type: 'Preorder', startDate: '2026-04-01',
    endDate: '2026-09-30', targetUnits: 500, sold: 355, targetRev: 67480, expMgn: 0.48, status: 'aktiv',
    note: 'Reminder-Kampagne – Ziel zu 71% erreicht' },
  { id: 'A003', name: 'Stadion Bundle-Aktion Herbst', productId: 'P011', type: 'Bundle', startDate: '2026-09-01',
    endDate: '2026-11-30', targetUnits: 50, sold: 0, targetRev: 13497, expMgn: 0.45, status: 'geplant',
    note: 'Launch Herbst 2026 vorbereiten' },
  { id: 'A004', name: 'Einzelstein-Box Sommer-Sale', productId: 'P006', type: 'Rabatt', startDate: '2026-07-01',
    endDate: '2026-08-31', targetUnits: 200, sold: 47, targetRev: 3990, expMgn: 0.38, status: 'aktiv',
    note: 'Cross-Sell LED-Kit prüfen' },
  { id: 'A005', name: 'Speicherstadt Early Bird Launch', productId: 'P002', type: 'Goodie', startDate: '2026-07-15',
    endDate: '2026-08-15', targetUnits: 100, sold: 0, targetRev: 12995, expMgn: 0.44, status: 'geplant',
    note: 'Goodie Teiletrenner + Poster kombinieren' },
  { id: 'A006', name: 'Fernsehturm Demo-Abverkaufsaktion', productId: 'P001', type: 'Abverkauf', startDate: '2026-06-29',
    endDate: '2026-07-31', targetUnits: 38, sold: 14, targetRev: 8548, expMgn: 0.50, status: 'aktiv',
    note: 'Erstellt via Demo-Skript Flow 1' },
  { id: 'A007', name: 'Alte Försterei Preispositionierung', productId: 'P003', type: 'Abverkauf', startDate: '2026-07-01',
    endDate: '2026-08-31', targetUnits: 30, sold: 0, targetRev: 4198, expMgn: 0.42, status: 'geplant',
    note: 'Via Demo-Skript Flow 4. Linked N009.' },
];

export const GOODIES: BpmGoodie[] = [
  { id: 'G001', name: 'Teiletrenner 3er-Set', type: 'Goodie', cost: 1.50, price: 0,
    products: ['P001', 'P002', 'P003', 'P004'], minCart: 49.95, validFrom: '2026-01-01', validTo: '2026-12-31',
    status: 'aktiv', mgnEffect: -1.50, comment: 'Standard-Goodie für alle Architektur- und Stadion-Sets' },
  { id: 'G002', name: 'Mini-Figur Berliner Bär', type: 'Goodie', cost: 3.80, price: 0,
    products: ['P001', 'P010'], minCart: 149.95, validFrom: '2026-01-01', validTo: '2026-07-31',
    status: 'aktiv', mgnEffect: -3.80, comment: 'Exklusiv für Berliner Produkte. Limitiert.' },
  { id: 'G003', name: 'Preorder Poster Skyline Berlin', type: 'Goodie', cost: 2.20, price: 0,
    products: ['P010'], minCart: 0, validFrom: '2026-04-01', validTo: '2026-09-30',
    status: 'aktiv', mgnEffect: -2.20, comment: 'Standardmäßig bei Preorder inklusive' },
  { id: 'G004', name: 'Sammlerzertifikat Limited Edition', type: 'Goodie', cost: 0.80, price: 0,
    products: ['P001'], minCart: 0, validFrom: '2026-01-01', validTo: null,
    status: 'aktiv', mgnEffect: -0.80, comment: 'Nummeriertes Zertifikat. Hoher wahrgenommener Wert bei Sammlern.' },
  { id: 'G005', name: 'Display Case Rabatt 15%', type: 'Bundle', cost: 7.49, price: 42.46,
    products: ['P002', 'P003', 'P004'], minCart: 89.95, validFrom: '2026-06-01', validTo: '2026-08-31',
    status: 'inaktiv', mgnEffect: -7.49, comment: 'Geplant für Sommer-Aktion. Noch nicht aktiviert.' },
  { id: 'G006', name: 'LED-Kit Bundle-Rabatt 20%', type: 'Bundle', cost: 7.99, price: 31.96,
    products: ['P002', 'P005'], minCart: 89.95, validFrom: '2026-07-01', validTo: '2026-09-30',
    status: 'geplant', mgnEffect: -7.99, comment: 'LED-Kit als Bundle-Ergänzung für Architektur-Sets' },
];

export const COMPETITORS: BpmCompetitor[] = [
  { id: 'C001', productId: 'P001', competitor: 'BrickMarket', compProduct: 'Berlin Tower Collector 2026',
    ownPrice: 249.95, compPrice: 234.95, avail: true, date: '2026-06-28', rec: 'Preispositionierung prüfen – 6,4% über Wettbewerb' },
  { id: 'C002', productId: 'P003', competitor: 'Klemmhelden Store', compProduct: 'Union Stadion Baukasten',
    ownPrice: 139.95, compPrice: 119.95, avail: true, date: '2026-06-27', rec: '16,7% über Wettbewerb – Aktion oder Begründung nötig' },
  { id: 'C003', productId: 'P004', competitor: 'ModelBrick World', compProduct: 'Frankfurt Arena Klemmset',
    ownPrice: 169.95, compPrice: 159.95, avail: false, date: '2026-06-25', rec: 'Wettbewerber nicht verfügbar – Preismacht nutzen' },
  { id: 'C004', productId: 'P002', competitor: 'BlueBrick Shop', compProduct: 'Speicherstadt Hamburg Edition',
    ownPrice: 129.95, compPrice: 124.95, avail: true, date: '2026-06-26', rec: '3,8% über Wettbewerb – akzeptabel bei Premium-Positionierung' },
  { id: 'C005', productId: 'P011', competitor: 'Baustein-Kontor', compProduct: 'Doppelpack Arenen-Set',
    ownPrice: 269.95, compPrice: 239.95, avail: true, date: '2026-06-28', rec: '12,5% über Wettbewerb – Bundle-Mehrwert kommunizieren' },
  { id: 'C006', productId: 'P012', competitor: 'BrickMarket', compProduct: 'LED-Set Architektur-Modelle',
    ownPrice: 39.95, compPrice: 44.95, avail: true, date: '2026-06-24', rec: 'Günstiger als Wettbewerb – Preiserhöhung prüfen' },
  { id: 'C007', productId: 'P006', competitor: 'Klemmhelden Store', compProduct: 'Basic Stein-Set 500tlg',
    ownPrice: 19.95, compPrice: 17.95, avail: true, date: '2026-06-23', rec: '11,1% über Wettbewerb – Sommer-Sale sinnvoll' },
  { id: 'C008', productId: 'P013', competitor: 'ModelBrick World', compProduct: 'Acryl Vitrine XL',
    ownPrice: 49.95, compPrice: 54.95, avail: true, date: '2026-06-22', rec: 'Günstiger als Wettbewerb – Positionierung stark' },
];

export const NOTIFICATIONS: BpmNotification[] = [
  { id: 'N001', type: 'Bestand', priority: 'kritisch', refId: 'P001',
    msg: 'Limited Edition Berliner Fernsehturm: Nur noch 38 Stück (Mindestbestand: 50). Abverkauf oder Nachproduktion entscheiden.',
    action: 'Abverkaufsaktion starten', status: 'offen', due: '2026-07-05', role: 'Produktmanager', target: 'Sortiment, Aktionen', note: null },
  { id: 'N002', type: 'Wettbewerb', priority: 'hoch', refId: 'P003',
    msg: 'Alte Försterei liegt 16,7% über Wettbewerbspreis (Klemmhelden: 119,95 € vs. 139,95 €). Preispositionierung prüfen.',
    action: 'Preispositionierung prüfen', status: 'offen', due: '2026-07-10', role: 'Produktmanager', target: 'Wettbewerb, Aktionen', note: null },
  { id: 'N003', type: 'Preorder', priority: 'hoch', refId: 'P010',
    msg: 'Preorder Skyline Berlin: Ziel zu 71% (355/500). Kampagnenende 30.09.2026 – Reminder-Kampagne vorbereiten.',
    action: 'Reminder-Kampagne starten', status: 'in Prüfung', due: '2026-07-15', role: 'Marketing', target: 'Aktionen, Newsletter', note: 'Stand 28.06.2026 geprüft' },
  { id: 'N004', type: 'Marge', priority: 'mittel', refId: 'P005',
    msg: 'Hafenkran: Aktionspreis 74,95 € → Marge 43,3%. Unter Zielmarge 45%, Mindestmarge gehalten.',
    action: 'Marge prüfen', status: 'offen', due: '2026-07-20', role: 'Produktmanager', target: 'Marge & Sales', note: null },
  { id: 'N005', type: 'Wettbewerb', priority: 'hoch', refId: 'P011',
    msg: 'Sammlerbundle Stadion Duo liegt 12,5% über Wettbewerb (Baustein-Kontor: 239,95 €). Bundle-Mehrwert kommunizieren.',
    action: 'Wettbewerbsprüfung starten', status: 'offen', due: '2026-07-08', role: 'Produktmanager', target: 'Wettbewerb, Aktionen', note: null },
  { id: 'N006', type: 'Aktion', priority: 'mittel', refId: 'A002',
    msg: 'Aktion "Preorder Skyline Berlin" endet 30.09.2026. Verlängerung oder Abschluss-Push planen.',
    action: 'Aktionsende planen', status: 'offen', due: '2026-09-16', role: 'Marketing', target: 'Aktionen', note: null },
  { id: 'N007', type: 'Schnittstelle', priority: 'niedrig', refId: '',
    msg: 'Shop-System: Letzter simulierter Sync vor 3 Tagen. Übergabe aktueller Produktdaten empfohlen.',
    action: 'Übergabe simulieren', status: 'offen', due: '2026-06-30', role: 'IT', target: 'Schnittstellen', note: null },
  { id: 'N008', type: 'Bestand', priority: 'mittel', refId: 'P005',
    msg: 'Hafenkran: Lagerbestand (12) unter Mindestbestand (20). Auslaufprodukt – Abverkauf abschließen.',
    action: 'Abverkauf abschließen', status: 'in Prüfung', due: '2026-07-31', role: 'Produktmanager', target: 'Sortiment', note: 'Abverkaufspreis angepasst am 15.06.2026' },
  { id: 'N009', type: 'Wettbewerb', priority: 'hoch', refId: 'P003',
    msg: 'Demo F4: Alte Försterei 16,7% über Wettbewerb. Klemmhelden: 119,95 €. Handlungsbedarf.',
    action: 'Preispositionierung prüfen', status: 'offen', due: '2026-07-06', role: 'Produktmanager', target: 'Wettbewerb, Aktionen', note: 'Via Demo-Skript Flow 4' },
];

export const INTEGRATIONS: BpmIntegration[] = [
  { id: 'I001', type: 'Shop-System', system: 'Shopware 6', purpose: 'Produktdaten, Preise, Aktionen, Bestände',
    objects: ['products', 'promotions', 'prices', 'inventory'], dir: 'BrickPM → Shop', status: 'bereit',
    ep: '/api/products', lastSync: '2026-06-25 14:32' },
  { id: 'I002', type: 'Warenwirtschaft / ERP', system: 'Xentral', purpose: 'Bestellungen, Lagerbestand, Lieferanten',
    objects: ['inventory', 'orders', 'suppliers'], dir: 'ERP → BrickPM', status: 'konfiguriert',
    ep: '/api/inventory', lastSync: '2026-06-26 09:15' },
  { id: 'I003', type: 'PIM', system: 'Akeneo', purpose: 'Produktstammdaten, Medien, Beschreibungen',
    objects: ['products', 'media', 'categories'], dir: 'PIM → BrickPM', status: 'geplant',
    ep: '/api/products', lastSync: '–' },
  { id: 'I004', type: 'CRM / Kundenservice', system: 'HubSpot', purpose: 'Kundenkontakte, Tickets, Kampagnen',
    objects: ['customers', 'tickets', 'campaigns'], dir: 'BrickPM → CRM', status: 'bereit',
    ep: '/api/notifications', lastSync: '2026-06-27 11:00' },
  { id: 'I005', type: 'Analytics', system: 'Matomo', purpose: 'Web-Tracking, Conversion, Seitenaufrufe',
    objects: ['events', 'pageviews', 'conversions'], dir: 'Shop → Analytics', status: 'aktiv',
    ep: '–', lastSync: 'laufend' },
  { id: 'I006', type: 'BI / Pricing', system: 'Power BI', purpose: 'Marge-Reports, Sales-Ziele, Preisanalyse',
    objects: ['marginScenarios', 'competitorPrices'], dir: 'BrickPM → BI', status: 'konfiguriert',
    ep: '/api/prices', lastSync: '2026-06-24 16:45' },
  { id: 'I007', type: 'Newsletter / Marketing', system: 'Klaviyo', purpose: 'Preorder-Reminder, Aktions-Mailings',
    objects: ['promotions', 'preorders', 'bundles'], dir: 'BrickPM → Marketing', status: 'bereit',
    ep: '/api/preorders', lastSync: '2026-06-28 08:30' },
  { id: 'I008', type: 'Versand / Fulfillment', system: 'DHL Versenden', purpose: 'Versandaufträge, Tracking, Retouren',
    objects: ['orders', 'shipments', 'returns'], dir: 'ERP → Fulfillment', status: 'geplant',
    ep: '/api/shipments', lastSync: '–' },
];
